#DEV environment
#Como teste foi usado o h2 como banco de dados 

app:
  message: This is the property file to the ${spring.application.name} specific to DEV environment

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa


